name: Enforce .editorconfig Rules and Check Build Warnings

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  format-and-build-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      # Step 3: Install dotnet-format
      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      # Step 4: Run dotnet format to verify .editorconfig rules
      - name: Run dotnet format
        run: dotnet format --verify-no-changes
        env:
          PATH: ${{ runner.tool_cache }}/dotnet:$PATH

      # Step 5: Build the project and capture warnings
      - name: Build the project
        run: dotnet build --configuration Release --no-restore /warnaserror
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      # Step 6: Fail the workflow if build warnings or errors are found
      - name: Check build result
        if: failure()
        run: |
          echo "Build warnings or errors detected. Please fix them before merging."
          exit 1
